# Trazemos a imagem do App que acabou de ser buildada para extrair os assets idênticos
FROM marketplace-app:latest AS app-image

# Main Nginx image
FROM nginx:alpine

# Copiamos as configurações
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Copiamos os arquivos estáticos (apenas a pasta public é necessária para o Nginx)
WORKDIR /var/www
COPY public /var/www/public

# Copiamos os assets buildados EXATAMENTE com o mesmo hash gerado no App
COPY --from=app-image /var/www/public/build /var/www/public/build

EXPOSE 80