# Stage 1: Build assets
FROM node:20-alpine AS assets-builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Main Nginx image
FROM nginx:alpine

# Copiamos as configurações
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Copiamos os arquivos estáticos (apenas a pasta public é necessária para o Nginx)
WORKDIR /var/www
COPY public /var/www/public

# Copiamos os assets buildados do Stage 1
COPY --from=assets-builder /app/public/build /var/www/public/build

EXPOSE 80